// packages/fact-composer-app/src/composition/pages/Composition.tsx
import {Fact} from "@repo/facts-db";
import {Button} from "~/components/ui/button";
import {FactList} from "../features/FactList";
import {Textarea} from "~/components/ui/textarea";
import {useAtom} from "jotai";
import {compositionAtom} from "../stores/compositionAtom";
import {useCallback} from "react";

export function Composition() {
  const {composition, setComposition, appendComposition} = useComposition();
  return (
    <div className="flex h-full gap-4 @container px-4">
      <div className="flex flex-col w-full h-full">
        <div className="flex justify-end">
          <Button>OK</Button>
        </div>
        <Textarea
          borderless
          className="w-full flex-grow"
          placeholder="Type or select a fact to start composing..."
          value={composition}
          onInput={e => setComposition(e.currentTarget.value)}
        />
      </div>
      <div className="w-full @lg:w-9/12 h-full py-2 px-3">
        <FactList onClick={appendComposition} />
      </div>
    </div>
  );
}

function useComposition() {
  const [composition, setComposition] = useAtom(compositionAtom);
  const appendComposition = useCallback(
    ({content}: Fact) =>
      setComposition($composition =>
        [$composition, content].filter(Boolean).join("\n"),
      ),
    [setComposition],
  );
  return {composition, setComposition, appendComposition} as const;
}

// packages/fact-composer/src/lib/composer/Composition.svelte
<script lang="ts">
  import * as Command from "$lib/components/ui/command";
  import type {FactsORM, Fact} from "@repo/facts-db";
  import { Textarea } from "$lib/components/ui/textarea";
  import CompositionEditor from "./CompositionEditor.svelte";

  export let placeholder = "";
  export let db: FactsORM;
  let query = "";
  let value = "";

  const facts = db.toObservable(() => db.objects.getAll());

  const handleSelect = (fact: Fact) => {
    value = [value, fact.content].filter(Boolean).join("\n");
    query = "";
  };
</script>

<div class="flex gap-4 w-full min-h-[300px] max-h-[300px] max-w-[66vw] min-w-[66vw]">
  <div class="min-w-[33vw]">
    <Command.Input
      placeholder="Type to search..."
      autofocus
      bind:value={query}
    />
    <Command.List>
      <Command.Empty>
        No facts found.
      </Command.Empty>
      {#if $facts}
      {#each $facts as fact (fact.id)}
      <Command.Item onSelect={() => handleSelect(fact)}>
        {fact.content}
      </Command.Item>
      {/each}
      {/if}
    </Command.List>
  </div>
  <CompositionEditor
    placeholder={placeholder}
    bind:value={value}
  />
</div>
