// packages/fact-composer/src/lib/collection/components/FactEditorToolbar.svelte
<script lang="ts">
  import {Button} from "$lib/components/ui/button";
  import SelectLabels from "$lib/labels/SelectLabels.svelte";
  import type {InsertFact} from "@repo/facts-db";
  import type {Task} from "fp-ts/lib/Task";
  import {ArchiveXIcon, TagIcon} from "lucide-svelte";
  import ToolbarButton from "./ToolbarButton.svelte";

  export let fact: InsertFact;
  export let onCreate: Task<void>;
  export let onSave: Task<void>;
  export let onClose: Task<void>;
  export let onArchive: Task<void>;

  $: handler = "id" in fact ? onSave : onCreate;
  $: saveLabel = "id" in fact ? "Save" : "Create";
</script>

<div class="flex w-full">
  <div class="flex">
    <SelectLabels bind:selectedLabels={fact.labels} let:builder let:open>
      <ToolbarButton
        builders={[builder]}
        tooltip="Add Label"
        role="combobox"
        aria-expanded={open}
      >
        <TagIcon class="h-4 w-4" />
      </ToolbarButton>
    </SelectLabels>
    {#if "id" in fact}
      <ToolbarButton tooltip="Archive" on:click={onArchive}>
        <ArchiveXIcon class="h-4 w-4" />
      </ToolbarButton>
    {/if}
  </div>
  <div class="grow"></div>
  <Button variant="link" on:click={handler}>{saveLabel}</Button>
  <Button variant="link" on:click={onClose}>Cancel</Button>
</div>

// packages/fact-composer-app/src/pages/collection/components/FactEditorToolbar.tsx
import {Fact, InsertFact, Label} from "@repo/facts-db";
import {ArchiveXIcon, TagIcon} from "lucide-react";
import {IconButton} from "~/components/IconButton";
import {Button} from "~/components/ui/button";
import {SelectLabels} from "~/pages/labels/components/SelectLabels";

type TProps = {
  fact: Fact | InsertFact;
  onChange: (fact: Fact | InsertFact) => void;
  onArchive: (factId: Fact["id"]) => void;
  onClose: () => void;
};

export function FactEditorToolbar({
  fact,
  onArchive,
  onChange,
  onClose,
}: TProps) {
  const updateLabels = (labels: Label[]) => onChange({...fact, labels});
  return (
    <div className="flex w-full">
      <div className="flex">
        <SelectLabels
          selected={fact.labels}
          onSelect={label => updateLabels([...fact.labels, label])}
        >
          {({open}) => (
            <IconButton
              tooltip="Add Label"
              role="combobox"
              aria-expanded={open}
            >
              <TagIcon className="h-4 w-4" />
            </IconButton>
          )}
        </SelectLabels>
        {"id" in fact && (
          <IconButton
            tooltip="Archive"
            onClick={async () => {
              await onArchive(fact.id);
              onClose();
            }}
          >
            <ArchiveXIcon className="h-4 w-4" />
          </IconButton>
        )}
      </div>
      <div className="grow"></div>
      <Button variant="link" onClick={onClose}>
        Close
      </Button>
    </div>
  );
}
