// packages/fact-composer/src/App.svelte
<script lang="ts">
  import "./app.css";
  import Textarea from "$lib/components/ui/textarea/textarea.svelte";
  import ComposerModal from "$lib/composer/ComposerModal.svelte";
  import type {ORM} from "@repo/facts-db";

  export let facts: ORM<"facts">;

</script>

<Textarea />
<ComposerModal {facts} />

// packages/fact-composer-app/src/App.tsx
import "./index.css";
import {createMemoryAdapter, DbClient} from "@repo/facts-db";
import {Textarea} from "./components/ui/textarea";
import {Composer} from "./composer/Composer";
import {seedDb} from "./_mock/seedDb";

const db = new DbClient(createMemoryAdapter);
seedDb(db);
export default function App() {
  return (
    <>
      <Textarea />
      <Composer db={db} />
    </>
  );
}
