// packages/fact-composer/src/lib/collection/components/FactEditorToolbar.svelte
<script lang="ts">
  import {Button} from "$lib/components/ui/button";
  import SelectLabels from "$lib/labels/SelectLabels.svelte";
  import type {InsertFact} from "@repo/facts-db";
  import type {Task} from "fp-ts/lib/Task";
  import {ArchiveXIcon, TagIcon} from "lucide-svelte";
  import ToolbarButton from "./ToolbarButton.svelte";

  export let fact: InsertFact;
  export let onCreate: Task<void>;
  export let onSave: Task<void>;
  export let onClose: Task<void>;
  export let onArchive: Task<void>;

  $: handler = "id" in fact ? onSave : onCreate;
  $: saveLabel = "id" in fact ? "Save" : "Create";
</script>

<div class="flex w-full">
  <div class="flex">
    <SelectLabels bind:selectedLabels={fact.labels} let:builder let:open>
      <ToolbarButton
        builders={[builder]}
        tooltip="Add Label"
        role="combobox"
        aria-expanded={open}
      >
        <TagIcon class="h-4 w-4" />
      </ToolbarButton>
    </SelectLabels>
    {#if "id" in fact}
      <ToolbarButton tooltip="Archive" on:click={onArchive}>
        <ArchiveXIcon class="h-4 w-4" />
      </ToolbarButton>
    {/if}
  </div>
  <div class="grow"></div>
  <Button variant="link" on:click={handler}>{saveLabel}</Button>
  <Button variant="link" on:click={onClose}>Cancel</Button>
</div>

// packages/fact-composer/src/pages/collection/features/FactEditorToolbar.tsx
import type {
  FactSchema,
  InsertFactSchema,
  LabelSchema,
} from "@repo/collection-service-defs";
import {IO} from "fp-ts/lib/IO";
import {Reader} from "fp-ts/lib/Reader";
import {ArchiveXIcon, TagIcon} from "lucide-react";
import {useCallback} from "react";
import {IconButton} from "~/components/IconButton";
import {Button} from "~/components/ui/button";
import {SelectLabels} from "~/pages/labels/components/SelectLabels";
import {useArchiveFact} from "../hooks/useArchiveFact";

type TProps = {
  fact: FactSchema | InsertFactSchema;
  onChange: Reader<FactSchema | InsertFactSchema, void>;
  onClose: IO<void>;
};

export function FactEditorToolbar({fact, onChange, onClose}: TProps) {
  const {archiveFact} = useArchiveFact();
  const updateLabels = useCallback(
    (label: LabelSchema) =>
      onChange({...fact, labels: [...fact.labels, label]}),
    [onChange, fact],
  );
  const archive = useCallback(() => {
     
    "_id" in fact && archiveFact(fact as FactSchema);
    onClose();
  }, [fact, archiveFact, onClose]);

  return (
    <div className="flex w-full">
      <div className="flex items-center">
        <SelectLabels selected={fact.labels} onSelect={updateLabels}>
          {({open}) => (
            <IconButton
              tooltip="Add Label"
              role="combobox"
              aria-expanded={open}
            >
              <TagIcon className="h-4 w-4" />
            </IconButton>
          )}
        </SelectLabels>
        {"_id" in fact && (
          <IconButton tooltip="Archive" onClick={archive}>
            <ArchiveXIcon className="w-4 h-4" />
          </IconButton>
        )}
      </div>
      <div className="grow" />
      <Button variant="link" onClick={onClose}>
        Close
      </Button>
    </div>
  );
}
