// packages/fact-composer/src/lib/collection/components/CollectionNav.svelte
<script lang="ts">
  import CollectionNavItem from "./CollectionNavItem.svelte";
  import LabelIcon from "./LabelIcon.svelte";
  import type {Label} from "@repo/facts-db";
  import {ArchiveIcon, BookOpenTextIcon} from "lucide-svelte";

  export let labels: Label[];
  let selected: number = 0;
</script>

<CollectionNavItem isSelected={selected === -1} onClick={() => (selected = -1)}>
  <BookOpenTextIcon />
  Facts
</CollectionNavItem>
<CollectionNavItem isSelected={selected === 0} onClick={() => (selected = 0)}>
  <ArchiveIcon />
  Archive
</CollectionNavItem>
{#each labels as label (label.id)}
  <CollectionNavItem
    isSelected={selected === label.id}
    onClick={() => (selected = label.id)}
  >
    <LabelIcon />
    {label.name}
  </CollectionNavItem>
{/each}

// packages/fact-composer-app/src/collection/features/CollectionNav.tsx
import {useLocation, useNavigate} from "react-router-dom";
import {CollectionNavTabs} from "../components/CollectionNavTabs";
import {Label} from "@repo/facts-db";
import {ArchiveIcon, BookOpenTextIcon} from "lucide-react";
import {LabelIcon} from "../components/LabelIcon";
import {NavTab} from "~/lib/NavTab";
import {useMemo} from "react";

type TProps = {
  labels: Label[];
};

export function CollectionNav({labels}: TProps) {
  const location = useLocation();
  const navigate = useNavigate();
  const tabs = useCollectionNav(labels);

  return (
    <aside className="flex flex-col pr-10 py-5">
      <CollectionNavTabs
        tabs={tabs}
        activeRoute={location}
        onClick={navigate}
      />
    </aside>
  );
}

function useCollectionNav(labels: Label[]): NavTab[] {
  return useMemo(() => {
    return [
      {
        Icon: BookOpenTextIcon,
        name: "Facts",
        route: "/facts",
      },
      ...labels.map(label => ({
        Icon: LabelIcon,
        name: label.name,
        route: `/facts?label=${label.id}`,
      })),
      {
        Icon: ArchiveIcon,
        name: "Archive",
        route: "/facts/archive",
      },
    ];
  }, [labels]);
}
