// packages/fact-composer/src/lib/collection/FactCard.svelte
<script lang="ts">
  import {Card, CardContent, CardFooter} from "$lib/components/ui/card";
  import type {Fact} from "@repo/facts-db";
  import {selectedFact} from "./store/selectedFact";
  import {openFactEditor} from "./store/openFactEditor";
  import { cn } from "$lib/utils";

  export let fact: Fact;
  $: isSelected = "id" in $selectedFact && $selectedFact.id === fact.id;
  const selectFact = () => {
    $selectedFact = {...fact};
    $openFactEditor = true;
  };
</script>

<Card
  on:click={selectFact}
  class={cn([
    "group",
    "max-w-[200px] max-h-[200px] min-h-[100px]",
    "shadow-none hover:shadow hover:border-gray-300",
    "transition-shadow duration-100 ease-in-out",
    { "border-black hover:border-black": isSelected },
  ])}
>
  <CardContent>
    <p class="break-words cursor-default py-5">
      {fact.content.substring(0, 100)}
      {#if fact.content.length > 100}
        ...
      {/if}
    </p>
  </CardContent>
  {#if fact.labels}
    <CardFooter class="opacity-0 group-hover:opacity-100">
      {#each fact.labels as label (label.id)}
        {label.name.substring(0, 10)}
      {/each}
    </CardFooter>
  {/if}
</Card>

// packages/fact-composer-app/src/collection/components/FactCard.tsx
import {Fact, Label} from "@repo/facts-db";
import {Card, CardContent, CardFooter} from "~/components/ui/card";
import {cn} from "~/lib/utils";
import {LabelPills} from "~/labels/components/LabelPills";

type TProps = {
  fact: Fact;
  isHighlighted?: boolean;
  highlightedLabels?: Label[];
  onClick?: () => void;
  children?: React.ReactNode;
};

export function FactCard({
  fact,
  highlightedLabels,
  isHighlighted,
  onClick,
  children,
}: TProps) {
  return (
    <Card
      className={cn([
        "group w-full",
        "select-none",
        "shadow-none hover:shadow hover:border-gray-400",
        "transition-shadow duration-100 ease-in-out",
        {"border-black hover:border-black": isHighlighted},
      ])}
      onClick={onClick}
    >
      <CardContent>
        <div className="w-full">
          <p className="min-h-[100px] line-clamp-5 cursor-default pt-4 mb-2">
            {fact.content}
          </p>
          <div className="flex gap-1 flex-wrap">
            <LabelPills
              labels={fact.labels}
              highlightedLabels={highlightedLabels}
            />
          </div>
        </div>
      </CardContent>
      {children && (
        <CardFooter className="opacity-0 pb-4 group-hover:opacity-100">
          {children}
        </CardFooter>
      )}
    </Card>
  );
}
