// packages/fact-composer/src/lib/collection/components/FactCard.svelte
<script lang="ts">
  import {Card, CardContent, CardFooter} from "$lib/components/ui/card";
  import type {Fact} from "@repo/facts-db";
  import {cn} from "$lib/utils";
  import LabelPills from "$lib/labels/LabelPills.svelte";
  import FactCardFooter from "./FactCardFooter.svelte";

  export let fact: Fact;
  export let isSelected: boolean;
</script>

<Card
  class={cn([
    "group",
    "max-w-[200px]",
    "shadow-none hover:shadow hover:border-gray-400",
    "transition-shadow duration-100 ease-in-out",
    {"border-black hover:border-black": isSelected},
  ])}
  on:click
>
  <CardContent>
    <div class="w-full">
      <p class="min-h-[100px] line-clamp-5 cursor-default pt-4 mb-2">
        {fact.content}
      </p>
      <div class="flex gap-1 flex-wrap">
        <LabelPills labels={fact.labels} />
      </div>
    </div>
  </CardContent>
  <CardFooter class="opacity-0 pb-4 group-hover:opacity-100">
    <FactCardFooter {fact} />
  </CardFooter>
</Card>

// packages/fact-composer-app/src/collection/components/FactCard.tsx
import {Fact, Label} from "@repo/facts-db";
import {Card, CardContent, CardFooter} from "~/components/ui/card";
import {cn} from "~/lib/utils";
import {LabelPills} from "~/labels/components/LabelPills";

type TProps = {
  fact: Fact;
  isHighlighted?: boolean;
  highlightedLabels?: Label[];
  onClick?: () => void;
  children?: React.ReactNode;
};

export function FactCard({
  fact,
  highlightedLabels,
  isHighlighted,
  onClick,
  children,
}: TProps) {
  return (
    <Card
      className={cn([
        "group w-full",
        "select-none",
        "shadow-none hover:shadow hover:border-gray-400",
        "transition-shadow duration-100 ease-in-out",
        {"border-black hover:border-black": isHighlighted},
      ])}
      onClick={onClick}
    >
      <CardContent>
        <div className="w-full">
          <p className="min-h-[100px] line-clamp-5 cursor-default pt-4 mb-2">
            {fact.content}
          </p>
          <div className="flex gap-1 flex-wrap">
            <LabelPills
              labels={fact.labels}
              highlightedLabels={highlightedLabels}
            />
          </div>
        </div>
      </CardContent>
      {children && (
        <CardFooter className="opacity-0 pb-4 group-hover:opacity-100">
          {children}
        </CardFooter>
      )}
    </Card>
  );
}
