// packages/fact-composer/src/lib/collection/FactEditor.svelte
<script lang="ts">
  import {Button} from "$lib/components/ui/button";
  import UnstyledTextarea from "$lib/components/ui/textarea/UnstyledTextarea.svelte";
  import {injectDbClient} from "$lib/injectDbClient";
  import SelectLabels from "$lib/labels/SelectLabels.svelte";
  import type { Label } from "@repo/facts-db";
  import {selectedFact} from "./store/selectedFact";
  import LabelPills from "$lib/labels/LabelPills.svelte";
  import { labels } from "$lib/labels/store/labels";

  const db = injectDbClient();
  export let onClose: () => void;
  let fact = selectedFact
  let selectedLabels: Label[] = [];

  const save = async () => {
    if ("id" in $fact) {
      await db.facts.put($fact.id, $fact);
    } else {
      await db.facts.add($fact);
    }
    close();
  };
  const close = () => {
    $fact = {content: ""};
    onClose();
  };
</script>

<div class="flex flex-col w-full gap-4 px-3 py-4 border">
  <div class="flex w-full">
    <div class="flex">
      <SelectLabels bind:selectedLabels />
    </div>
    <div class="grow"></div>
    <Button variant="link" on:click={save}>Save</Button>
    <Button variant="link" on:click={close}>Cancel</Button>
  </div>
  <div class="flex gap-2">
    <LabelPills bind:labels={selectedLabels} />
  </div>
  <UnstyledTextarea
    autofocus
    class="w-full py-4 px-1 min-h-[120px] grow"
    placeholder="Add a Fact..."
    bind:value={$fact.content}
  />
</div>

// packages/fact-composer-app/src/collection/components/FactEditor.tsx
import {Fact, InsertFact, Label} from "@repo/facts-db";
import {Reader} from "fp-ts/lib/Reader";
import {useEffect, useState} from "react";
import {Textarea} from "~/components/ui/textarea";
import {LabelsEditor} from "~/labels/components/LabelsEditor";

type TProps = {
  fact: Fact | InsertFact;
  onChange: Reader<Fact | InsertFact, void>;
};

export function FactEditor({fact, onChange}: TProps) {
  const [content, setContent] = useState(fact.content);
  useEffect(() => {
    setContent(fact.content);
  }, [fact.content]);

  const updateContent = (content: string) => {
    setContent(content);
    onChange({...fact, content});
  };
  const updateLabels = (labels: Label[]) => onChange({...fact, labels});

  return (
    <div className="flex flex-col w-full h-full gap-4 px-3 py-4">
      <div className="flex gap-2 flex-wrap">
        <LabelsEditor labels={fact.labels} onChange={updateLabels} />
      </div>
      <Textarea
        autoFocus
        borderless
        className="w-full py-4 px-1 min-h-[120px] grow"
        placeholder="Add a Fact..."
        value={content}
        onInput={e => updateContent(e.currentTarget.value)}
      />
    </div>
  );
}
