// packages/fact-composer/src/lib/labels/SelectLabels.svelte
<script lang="ts">
  import Check from "svelte-radix/Check.svelte";
  import * as Command from "$lib/components/ui/command/index.js";
  import * as Popover from "$lib/components/ui/popover/index.js";
  import {Button} from "$lib/components/ui/button/index.js";
  import {cn} from "$lib/utils.js";
  import {labels} from "./store/labels";
  import type {Label} from "@repo/facts-db";
  import {injectDbClient} from "$lib/injectDbClient";

  const db = injectDbClient();
  export let selectedLabels: Label[];
  let open = false;
  let query = "";

  const selectLabel = (label: Label) => {
    const index = selectedLabels.findIndex(l => l.id === label.id);
    if (index !== -1) {
      selectedLabels.splice(index, 1);
    } else {
      selectedLabels.push(label);
    }
    selectedLabels = selectedLabels;
    open = false;
  };

  const isSelected = (label: Label) =>
    selectedLabels.some(l => l.id === label.id);

  const addAndSelectLabel = async () => {
    const id = await db.labels.add({name: query});
    selectLabel({id, name: query});
  };
</script>

<Popover.Root bind:open>
  <Popover.Trigger asChild let:builder>
    <slot {builder} {open} />
  </Popover.Trigger>
  <Popover.Content class="w-[200px] p-0">
    <Command.Root>
      <Command.Input
        bind:value={query}
        placeholder="Search labels..."
        class="h-9"
      />
      <Command.Empty>
        <p>No labels found</p>
        <Button
          variant="ghost"
          size="sm"
          class="w-full justify-start"
          on:click={addAndSelectLabel}
        >
          Add "{query}"
        </Button>
      </Command.Empty>
      {#each $labels as label (label.id)}
        <Command.Item value={label.name} onSelect={() => selectLabel(label)}>
          <Check
            class={cn("mr-2 h-4 w-4", !isSelected(label) && "text-transparent")}
          />
          {label.name}
        </Command.Item>
      {/each}
    </Command.Root>
  </Popover.Content>
</Popover.Root>

// packages/fact-composer/src/pages/labels/components/SelectLabels.tsx
import {Reader} from "fp-ts/lib/Reader";
import {Check} from "lucide-react";
import {useCallback, useEffect, useMemo, useState} from "react";
import {Button} from "~/components/ui/button";
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from "~/components/ui/command";
import {Popover, PopoverContent, PopoverTrigger} from "~/components/ui/popover";
import {cn} from "~/lib/utils";
import {LabelSchema} from "@repo/collection-service-defs";
import {useLabelActions} from "../hooks/useLabelActions";
import {useAtomValue} from "jotai";
import {queryLabelsAtom} from "../store/queryLabelsAtom";

type TProps = {
  children: Reader<{open: boolean}, React.ReactNode>;
  selected: LabelSchema[];
  onSelect: Reader<LabelSchema, void>;
};

export function SelectLabels({children, selected, onSelect}: TProps) {
  const {search, setSearch, labels} = useSelectLabelsQuery(selected);
  const {selectLabel, addAndSelect, open, setOpen} = useSelectLabels(
    search,
    onSelect,
  );
  useEffect(() => setSearch(""), [setSearch, open]);
  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>{children?.({open})}</PopoverTrigger>
      <PopoverContent className="w-[200px] p-0">
        <Command>
          <CommandInput
            className="h-9"
            onInput={e => setSearch(e.currentTarget.value)}
            placeholder="Search labels..."
          />
          <CommandList>
            <CommandEmpty>
              <Button
                variant="ghost"
                size="sm"
                className="w-full justify-start"
                onClick={addAndSelect}
              >
                Add "{search}"
              </Button>
            </CommandEmpty>
            <CommandGroup>
              {labels?.map(label => (
                <CommandItem
                  key={label._id}
                  value={label.name}
                  onSelect={() => selectLabel(label)}
                >
                  <Check
                    className={cn(
                      "mr-2 h-4 w-4",
                      !selected.some(l => l._id === label._id) &&
                        "text-transparent",
                    )}
                  />
                  {label.name}
                </CommandItem>
              ))}
            </CommandGroup>
          </CommandList>
        </Command>
      </PopoverContent>
    </Popover>
  );
}

function useSelectLabels(search: string, onSelect: TProps["onSelect"]) {
  const [open, setOpen] = useState(false);
  const {addLabel} = useLabelActions();
  const selectLabel = useCallback<Reader<LabelSchema, void>>(
    label => {
      onSelect(label);
      setOpen(false);
    },
    [onSelect],
  );
  const addAndSelect = useCallback(async () => {
    const addedLabel = await addLabel({name: search});
    if (addedLabel) {
      selectLabel(addedLabel);
    }
  }, [addLabel, selectLabel, search]);

  return {selectLabel, open, setOpen, addAndSelect};
}

function useSelectLabelsQuery(excludedLabels: LabelSchema[]) {
  const [search, setSearch] = useState("");
  const allLabels = useAtomValue(queryLabelsAtom);
  const excludedLabelIds = useMemo(
    () => excludedLabels.map(label => label._id),
    [excludedLabels],
  );
  const labels = useMemo(
    () =>
      allLabels
        .filter(label => !excludedLabelIds.includes(label._id))
        .filter(label =>
          label.name.toLowerCase().includes(search.toLowerCase()),
        )
        .slice(0, 7),
    [excludedLabelIds, search, allLabels],
  );
  return {search, setSearch, labels};
}
