// packages/fact-composer/src/lib/composition/FactListItem.svelte
<script lang="ts">
  import LabelPills from "$lib/labels/LabelPills.svelte";
  import {cn} from "$lib/utils";
  import type {Fact} from "@repo/facts-db";

  export let fact: Fact;
</script>

<!-- svelte-ignore a11y-click-events-have-key-events -->
<!-- svelte-ignore a11y-no-static-element-interactions -->
<div
  class={cn(
    "flex flex-col w-full gap-2 p-4 box-border",
    "border border-gray-200 rounded-lg",
    "transition",
    "hover:border-gray-400",
  )}
  on:click
>
  <span class="text-sm cursor-default">
    {fact.content}
  </span>
  <div class="flex gap-1">
    <LabelPills labels={fact.labels} />
  </div>
</div>

// packages/fact-composer-app/src/composition/components/FactListItem.tsx
import {Fact} from "@repo/facts-db";
import {ComponentProps} from "react";
import {LabelPills} from "~/labels/components/LabelPills";
import {cn} from "~/lib/utils";

type TProps = ComponentProps<"div"> & {
  fact: Fact;
};

export function FactListItem({fact, ...props}: TProps) {
  return (
    <div
      {...props}
      className={cn(
        "flex flex-col w-full gap-2 p-4 box-border",
        "border border-gray-200 rounded-lg",
        "transition",
        "hover:border-gray-400",
      )}
    >
      <span className="text-sm cursor-default">{fact.content}</span>
      <div className="flex gap-1">
        <LabelPills labels={fact.labels} />
      </div>
    </div>
  );
}
