// packages/fact-composer/src/components/EasyTooltip.tsx
import {ComponentProps} from "react";
import {Tooltip, TooltipContent, TooltipTrigger} from "~/components/ui/tooltip";

type TProps = ComponentProps<typeof TooltipContent> & {
  children: React.ReactNode;
  openDelay?: number;
  tooltip: string;
};

export function EasyTooltip({
  children,
  openDelay,
  tooltip,
  ...contentProps
}: TProps) {
  return (
    <Tooltip delayDuration={openDelay}>
      <TooltipTrigger asChild>{children}</TooltipTrigger>
      <TooltipContent {...contentProps}>
        <span className="capitalize">{tooltip}</span>
      </TooltipContent>
    </Tooltip>
  );
}

// packages/fact-composer/src/lib/components/EasyTooltip.svelte
<script lang="ts">
  import type {ComponentProps} from "svelte";
  import {Tooltip, TooltipTrigger} from "./ui/tooltip";
  import TooltipContent from "./ui/tooltip/tooltip-content.svelte";

  export let tooltip: string;
  export let side: ComponentProps<TooltipContent>["side"] = "bottom";
  export let openDelay: number = 500;
  export let sideOffset: number = 0;
</script>

<Tooltip {openDelay}>
  <TooltipTrigger>
    <slot />
  </TooltipTrigger>
  <TooltipContent {side} {sideOffset}>
    <span class="capitalize text-xs">{tooltip}</span>
  </TooltipContent>
</Tooltip>
