// packages/fact-composer-app/src/collection/labels/components/LabelPills.tsx
import {Label} from "@repo/facts-db";
import {Pill} from "~/components/Pill";
import {Reader} from "fp-ts/Reader";
import _isequal from "lodash.isequal";

type TProps = {
  labels: Label[];
  highlightedLabels?: Label[];
  slot?: Reader<Label, React.ReactNode>;
  onClick?: Reader<Label, void>;
  className?: string;
};

export function LabelPills({
  labels,
  highlightedLabels,
  slot,
  onClick,
  className,
}: TProps) {
  return labels
    .map(label => (
      <Pill
        key={label.id}
        name={label.name}
        className={className}
        variant={toVariant(label, highlightedLabels)}
        onClick={() => onClick?.(label)}
      >
        {slot?.(label)}
      </Pill>
    ))
    .sort((a, b) => {
      if (a.props.variant === "default") {
        return -1;
      }
      if (b.props.variant === "default") {
        return 1;
      }
      return 0;
    });
}

function toVariant(label: Label, highlightedLabels?: Label[]) {
  return highlightedLabels?.some($label => _isequal($label, label))
    ? "default"
    : "outline";
}

// packages/fact-composer/src/lib/labels/LabelPills.svelte
<script lang="ts">
  import {Badge} from "$lib/components/ui/badge";
  import {Button} from "$lib/components/ui/button";
  import type {Label} from "@repo/facts-db";
  import {XIcon} from "lucide-svelte";

  export let labels: Label[];
</script>

{#each labels as label (label.id)}
  <Badge variant="outline">
    <span class="inline-flex items-center relative">
      {label.name}
      <slot {label} />
    </span>
  </Badge>
{/each}
